name: Deploy to EC2

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      run: |
        ssh -i ./atul_pandey_ubuntu.pem ec2_user@52.87.183.248 "touch example.txt"
